/*
 * gcl_icon.c — see gcl_icon.h.
 *
 * Windows:
 *   The built programme is a COPY of gcl.exe. Instead of re-linking (which is
 *   impossible on an already-built binary) the icon is written into the copy's
 *   PE resources with the Win32 resource-update API:
 *       BeginUpdateResourceA / UpdateResourceA / EndUpdateResourceA
 *   A single PNG-compressed RT_ICON entry is stored together with the matching
 *   RT_GROUP_ICON directory (Vista+ supports PNG payloads inside icons), so
 *   Explorer, the taskbar and Alt-Tab all use the project icon.
 *
 * Linux:
 *   ELF files carry no icon, so the icon is materialised next to the executable
 *   as "<project_name>.png" plus a "<project_name>.desktop" launcher whose
 *   Icon=/Exec= keys point at it — the same user-visible result as Windows.
 *
 * The default icon used by `gcl -new` comes from _SRC/embed_icon.c, generated
 * by makefile.py from the repository's assets/icon.png (embed_icon()).
 */

#include "gcl_icon.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

/* Generated by makefile.py — the default gnuchan logo PNG bytes. */
extern const unsigned char gcl_embed_icon_png[];
extern const unsigned int gcl_embed_icon_png_size;

/* ----- last-error reporting -------------------------------------------- */

static char g_icon_error[256];

static void icon_set_error(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(g_icon_error, sizeof(g_icon_error), fmt, ap);
    va_end(ap);
}

const char *gcl_icon_last_error(void) {
    return g_icon_error[0] ? g_icon_error : "no error";
}

/* ------------------------------------------------------------------ paths */

#define GCL_ICON_PATH_MAX 4096

/* Regular file check (mirrors gcl_main.c's path_is_dir style). */
static int icon_is_file(const char *p) {
    if (!p || !p[0]) return 0;
#ifdef _WIN32
    struct _stat st;
    if (_stat(p, &st) != 0) return 0;
    return (st.st_mode & _S_IFREG) != 0;
#else
    struct stat st;
    if (stat(p, &st) != 0) return 0;
    return S_ISREG(st.st_mode) != 0;
#endif
}

/* Directory part of a path ("a/b/c.exe" -> "a/b"); empty when there is none. */
static void icon_parent_dir(const char *path, char *out, size_t outsz) {
    if (!out || outsz == 0) return;
    out[0] = '\0';
    if (!path) return;
    size_t n = strlen(path);
    if (n >= outsz) n = outsz - 1;
    memcpy(out, path, n);
    out[n] = '\0';
    char *slash = strrchr(out, '\\');
    char *slash2 = strrchr(out, '/');
    if (!slash || (slash2 && slash2 > slash)) slash = slash2;
    if (slash) *slash = '\0';
}

/* Absolute form of path (POSIX realpath, Win32 _fullpath); falls back to the
   input when the call fails — the desktop file is still usable that way. */
static void icon_absolute_path(const char *path, char *out, size_t outsz) {
    if (!out || outsz == 0) return;
    out[0] = '\0';
    if (!path) return;
#ifdef _WIN32
    if (_fullpath(out, path, outsz) == NULL)
        snprintf(out, outsz, "%s", path);
#else
    if (realpath(path, out) == NULL)
        snprintf(out, outsz, "%s", path);
#endif
}

/* ------------------------------------------------------------------- I/O */

static unsigned char *icon_read_file(const char *path, size_t *out_size) {
    if (out_size) *out_size = 0;
    if (!path || !path[0]) return NULL;
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    rewind(f);
    unsigned char *buf = (unsigned char *)malloc((size_t)sz + 1);
    if (!buf) { fclose(f); return NULL; }
    size_t rd = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    buf[rd] = '\0';
    if (out_size) *out_size = rd;
    return buf;
}

static int icon_write_file(const char *path, const void *data, size_t size) {
    if (!path || !path[0]) return -1;
    FILE *f = fopen(path, "wb");
    if (!f) return -1;
    size_t wr = size ? fwrite(data, 1, size, f) : 0;
    fclose(f);
    return (wr == size) ? 0 : -1;
}

static int icon_copy_file(const char *src, const char *dst) {
    size_t n = 0;
    unsigned char *data = icon_read_file(src, &n);
    if (!data) return -1;
    int rc = icon_write_file(dst, data, n);
    free(data);
    return rc;
}

/* ---------------------------------------------- project.gcdata "icon" key */

/* Extracts a string value from a small JSON-ish document:
       "icon": "assets/icon.png"   ->   assets/icon.png
   Returns 0 when the key is found, -1 otherwise. Trailing comments or extra
   keys after the value are irrelevant (parsing stops at the closing quote). */
static int json_string_field(const char *json, const char *key,
                             char *out, size_t outsz) {
    if (!json || !key || !out || outsz == 0) return -1;
    out[0] = '\0';

    char pattern[128];
    int n = snprintf(pattern, sizeof(pattern), "\"%s\"", key);
    if (n < 0 || (size_t)n >= sizeof(pattern)) return -1;

    const char *p = strstr(json, pattern);
    if (!p) return -1;
    p += strlen(pattern);
    p = strchr(p, ':');
    if (!p) return -1;
    p++;
    while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
    if (*p != '"') return -1;
    p++;
    const char *e = strchr(p, '"');
    if (!e) return -1;

    size_t len = (size_t)(e - p);
    if (len >= outsz) len = outsz - 1;
    memcpy(out, p, len);
    out[len] = '\0';
    return 0;
}

/* Reads <project_dir>/project.gcdata and resolves the "icon" value to a path.
   Relative values are resolved against project_dir.
   Returns 0 on success, -1 when the file/key is missing or too long. */
static int resolve_project_icon(const char *project_dir, char *out, size_t outsz) {
    if (!project_dir || !project_dir[0] || !out || outsz == 0) return -1;
    out[0] = '\0';

    char gcdata[GCL_ICON_PATH_MAX];
    int n = snprintf(gcdata, sizeof(gcdata), "%s/project.gcdata", project_dir);
    if (n < 0 || (size_t)n >= sizeof(gcdata)) return -1;

    size_t txt_sz = 0;
    char *txt = (char *)icon_read_file(gcdata, &txt_sz);
    if (!txt) return -1;

    char rel[2048];
    int rc = json_string_field(txt, "icon", rel, sizeof(rel));
    free(txt);
    if (rc != 0 || !rel[0]) return -1;

    int absolute = (rel[0] == '/' || rel[0] == '\\');
#ifdef _WIN32
    if (!absolute && rel[1] == ':') absolute = 1;
#endif
    if (absolute) {
        n = snprintf(out, outsz, "%s", rel);
    } else {
        n = snprintf(out, outsz, "%s/%s", project_dir, rel);
    }
    if (n < 0 || (size_t)n >= outsz) return -1;
    return 0;
}
/* ------------------------------------------------------------- Windows PE */

#ifdef _WIN32

/* PNG header parse — width is the big-endian u32 at offset 16, height at 20
   (8-byte signature + 4-byte length + "IHDR"). */
static void png_dimensions(const unsigned char *d, size_t n, int *w, int *h) {
    *w = 0;
    *h = 0;
    if (!d || n < 24) return;
    if (!(d[0] == 0x89 && d[1] == 'P' && d[2] == 'N' && d[3] == 'G')) return;
    unsigned int ww = ((unsigned int)d[16] << 24) | ((unsigned int)d[17] << 16)
                    | ((unsigned int)d[18] << 8)  |  (unsigned int)d[19];
    unsigned int hh = ((unsigned int)d[20] << 24) | ((unsigned int)d[21] << 16)
                    | ((unsigned int)d[22] << 8)  |  (unsigned int)d[23];
    *w = (int)(ww & 0x7fffffffu);
    *h = (int)(hh & 0x7fffffffu);
}

#pragma pack(push, 2)
typedef struct {
    WORD idReserved;
    WORD idType;
    WORD idCount;
} GclGrpIconDir;

typedef struct {
    BYTE  bWidth;
    BYTE  bHeight;
    BYTE  bColorCount;
    BYTE  bReserved;
    WORD  wPlanes;
    WORD  wBitCount;
    DWORD dwBytesInRes;
    WORD  nID;
} GclGrpIconEntry;
#pragma pack(pop)

/* Resource ids the build may have written previously. Deleting this range
   keeps repeated builds idempotent (no accumulating stale icons). */
#define GCL_ICON_ID      1
#define GCL_ICON_MAX_ID  32

static int win_apply_icon_bytes(const unsigned char *png, size_t png_sz,
                                const char *exe_path) {
    if (!png || png_sz < 24 || !exe_path || !exe_path[0]) {
        icon_set_error("icon payload or target path missing");
        return -1;
    }

    int w = 0, h = 0;
    png_dimensions(png, png_sz, &w, &h);

    SetLastError(0);
    HANDLE upd = BeginUpdateResourceA(exe_path, FALSE);
    if (!upd) {
        icon_set_error("BeginUpdateResourceA failed for '%s' (Win32 error %lu)",
                       exe_path, (unsigned long)GetLastError());
        return -1;
    }

    for (int id = 1; id <= GCL_ICON_MAX_ID; id++) {
        UpdateResourceA(upd, RT_ICON, MAKEINTRESOURCEA(id), LANG_NEUTRAL, NULL, 0);
        UpdateResourceA(upd, RT_GROUP_ICON, MAKEINTRESOURCEA(id), LANG_NEUTRAL, NULL, 0);
    }

    /* Vista+ accepts a PNG payload inside RT_ICON (no BMP/ICO conversion). */
    SetLastError(0);
    BOOL ok = UpdateResourceA(upd, RT_ICON, MAKEINTRESOURCEA(GCL_ICON_ID),
                              LANG_NEUTRAL, png, (DWORD)png_sz);
    DWORD res_err = ok ? 0 : GetLastError();
    if (!ok)
        icon_set_error("UpdateResourceA(RT_ICON) failed (%lu bytes, Win32 error %lu)",
                       (unsigned long)png_sz, (unsigned long)res_err);
    (void)res_err;

    GclGrpIconDir dir;
    dir.idReserved = 0;
    dir.idType = 1;
    dir.idCount = 1;

    GclGrpIconEntry ent;
    memset(&ent, 0, sizeof(ent));
    /* 0 means 256 in the ICONDIR encoding. */
    ent.bWidth      = (BYTE)((w >= 256 || w <= 0) ? 0 : w);
    ent.bHeight     = (BYTE)((h >= 256 || h <= 0) ? 0 : h);
    ent.bColorCount = 0;
    ent.wPlanes     = 1;
    ent.wBitCount   = 32;
    ent.dwBytesInRes = (DWORD)png_sz;
    ent.nID         = GCL_ICON_ID;

    unsigned char grp[sizeof(GclGrpIconDir) + sizeof(GclGrpIconEntry)];
    memcpy(grp, &dir, sizeof(dir));
    memcpy(grp + sizeof(dir), &ent, sizeof(ent));

    if (ok) {
        SetLastError(0);
        ok = UpdateResourceA(upd, RT_GROUP_ICON, MAKEINTRESOURCEA(GCL_ICON_ID),
                             LANG_NEUTRAL, grp, (DWORD)sizeof(grp));
        if (!ok)
            icon_set_error("UpdateResourceA(RT_GROUP_ICON) failed (Win32 error %lu)",
                           (unsigned long)GetLastError());
    }

    if (!EndUpdateResourceA(upd, FALSE)) {
        DWORD end_err = GetLastError();
        if (ok)
            icon_set_error("EndUpdateResourceA failed (Win32 error %lu)",
                           (unsigned long)end_err);
        ok = FALSE;
    }

    return ok ? 0 : -1;
}

#else /* -------------------------------------------------------- Linux / ELF */

static int linux_apply_icon_bytes(const unsigned char *png, size_t png_sz,
                                  const char *exe_path, const char *project_name) {
    if (!png || png_sz == 0) return -1;

    char exe_dir[GCL_ICON_PATH_MAX];
    icon_parent_dir(exe_path, exe_dir, sizeof(exe_dir));
    if (!exe_dir[0]) return -1;

    /* The icon lives next to the executable, named after the project — the
       same convention desktop environments look for. */
    char icon_dst[GCL_ICON_PATH_MAX * 2];
    int n = snprintf(icon_dst, sizeof(icon_dst), "%s/%s.png", exe_dir, project_name);
    if (n < 0 || (size_t)n >= sizeof(icon_dst)) return -1;
    if (icon_write_file(icon_dst, png, png_sz) != 0) return -1;

    char abs_exe[GCL_ICON_PATH_MAX * 2];
    char abs_icon[GCL_ICON_PATH_MAX * 2];
    icon_absolute_path(exe_path, abs_exe, sizeof(abs_exe));
    icon_absolute_path(icon_dst, abs_icon, sizeof(abs_icon));

    char desktop[GCL_ICON_PATH_MAX * 2];
    n = snprintf(desktop, sizeof(desktop), "%s/%s.desktop", exe_dir, project_name);
    if (n < 0 || (size_t)n >= sizeof(desktop)) return -1;

    char text[GCL_ICON_PATH_MAX * 8];
    n = snprintf(text, sizeof(text),
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Version=1.0\n"
        "Name=%s\n"
        "Comment=%s built with GCL\n"
        "Exec=\"%s\"\n"
        "Icon=%s\n"
        "Path=%s\n"
        "Terminal=false\n"
        "Categories=Game;Development;\n",
        project_name, project_name, abs_exe, abs_icon, exe_dir);
    if (n < 0 || (size_t)n >= sizeof(text)) return -1;
    if (icon_write_file(desktop, text, strlen(text)) != 0) return -1;

    chmod(desktop, 0755);
    chmod(exe_path, 0755);   /* cp may not preserve the executable bit */
    return 0;
}

#endif /* _WIN32 */

/* --------------------------------------------------------------- public */

int gcl_icon_apply_project(const char *project_dir, const char *exe_path,
                           const char *project_name) {
    if (!project_dir || !project_dir[0] || !exe_path || !exe_path[0]) return -1;

    /* Icon resolution, in order of preference. Each fallback exists so a build
       ALWAYS produces an icon — old projects (created before the "icon" key
       existed) and projects whose PNG was deleted used to fail silently and
       the produced exe kept the plain gcl.exe icon. */
    size_t png_sz = 0;
    unsigned char *png = NULL;

    /* 1) the path named by "icon" in project.gcdata */
    char png_path[GCL_ICON_PATH_MAX];
    if (resolve_project_icon(project_dir, png_path, sizeof(png_path)) == 0
        && icon_is_file(png_path)) {
        png = icon_read_file(png_path, &png_sz);
    }

    /* 2) the conventional location <project>/assets/icon.png */
    if (!png) {
        char def[GCL_ICON_PATH_MAX];
        int n = snprintf(def, sizeof(def), "%s/%s", project_dir, GCL_ICON_REL_PATH);
        if (n > 0 && (size_t)n < sizeof(def) && icon_is_file(def))
            png = icon_read_file(def, &png_sz);
    }

    /* 3) the icon embedded in the build (the same one -new writes out) */
    if (!png && gcl_embed_icon_png_size > 0) {
        png = (unsigned char *)malloc((size_t)gcl_embed_icon_png_size);
        if (png) {
            memcpy(png, gcl_embed_icon_png, (size_t)gcl_embed_icon_png_size);
            png_sz = (size_t)gcl_embed_icon_png_size;
        }
    }

    if (!png || png_sz < 24) {
        icon_set_error(png
            ? "the icon file is too small to be a PNG"
            : "no icon found (no \"icon\" key in project.gcdata, no assets/icon.png, "
              "no embedded icon)");
        free(png);
        return -1;
    }

    int rc;
#ifdef _WIN32
    (void)project_name;
    rc = win_apply_icon_bytes(png, png_sz, exe_path);
#else
    rc = linux_apply_icon_bytes(png, png_sz, exe_path,
                                (project_name && project_name[0]) ? project_name : "project");
#endif
    free(png);
    return rc;
}

int gcl_icon_write_default(const char *dst_path) {
    if (!dst_path || !dst_path[0]) return -1;
    if (gcl_embed_icon_png_size == 0) return -1;
    return icon_write_file(dst_path, gcl_embed_icon_png,
                           (size_t)gcl_embed_icon_png_size);
}
