winetricks -q d3dx11_43 
winetricks -q dotnet40 
winetricks -q dotnet45 
winetricks -q dotnet461 
winetricks -q dotnet462 
winetricks -q dotnet46 
winetricks -q dotnet471 
winetricks -q dotnet472 
winetricks -q dotnet48 
winetricks -q mfc42

winetricks -q corefonts 
winetricks -q tahoma 
winetricks -q allfonts 
winetricks -q dotnet40 
winetricks -q vcrun6 
winetricks -q vcrun2005 
winetricks -q vcrun2008 
winetricks -q vcrun2010 
winetricks -q vcrun2012 
winetricks -q vcrun2013 
winetricks -q vcrun2015 
winetricks -q vcrun2019 
winetricks -q d3dx9 
winetricks -q wmp10 
winetricks -q ie8 
winetricks -q flash 
winetricks -q silverlight 
winetricks -q jre8 
winetricks -q allcodecs