# Backend ve performans
backend = "glx";
vsync = true;

# Köşe yuvarlama
corner-radius = 10;
detect-rounded-corners = true;

# Blur
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 5;

# Opacity algılama
detect-client-opacity = true;

# Performans
unredir-if-possible = true;

# Tüm pencerelere kural
rules = (
  {
    class = ".*";
    opacity = 0.85;
    inactive = true;
    rounded-corners = true;
  }
);
