# Backend ve performans
backend = "glx";
vsync = true;

# Köşe yuvarlama
corner-radius = 10;
detect-rounded-corners = true;

# Blur
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 5;

# Opacity algılama
detect-client-opacity = true;

# Performans
unredir-if-possible = true;

# Shadow
shadow = true;
shadow-color = "#6f00ff";
shadow-opacity = 1.2;

# Tüm pencerelere kural
rules = (
  {
    match = "class_g = 'XTerm'";
    opacity = 0.65;
  }
)



