#!/bin/bash

xterm&

# disable sleep mode
xset -dpms &
xset s off &

# Start the conky to learn the shortcuts
picom --config ~/.config/openbox/picom.conf &

# default app
xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop &

nitrogen --head=0 --set-scaled ~/.config/qtile/bg.png &
nitrogen  --restore &

stty erase ^H &
dunst &
xfce4-panel &
