/* Codegen: AST'den C kodu uretir */
#include "gcl.h"
#include "ast.h"

static void emit_expr(FILE *out, Node *n);

static const char *op_c(TokenType t) {
    switch (t) {
    case T_PLUS: return "+"; case T_MINUS: return "-";
    case T_STAR: return "*"; case T_SLASH: return "/";
    case T_PERCENT: return "%";
    case T_AMPERSAND: return "&"; case T_PIPE: return "|";
    case T_CARET: return "^"; case T_TILDE: return "~";
    case T_LSHIFT: return "<<"; case T_RSHIFT: return ">>";
    case T_EQ: return "=="; case T_NE: return "!=";
    case T_LT: return "<"; case T_GT: return ">";
    case T_LE: return "<="; case T_GE: return ">=";
    case T_AND: return "&&"; case T_OR: return "||";
    case T_NOT: return "!"; case T_INC: return "++";
    case T_DEC: return "--";
    case T_ASSIGN: return "="; case T_ADD_ASSIGN: return "+=";
    case T_SUB_ASSIGN: return "-="; case T_MUL_ASSIGN: return "*=";
    case T_DIV_ASSIGN: return "/="; case T_MOD_ASSIGN: return "%=";
    case T_AND_ASSIGN: return "&="; case T_OR_ASSIGN: return "|=";
    case T_XOR_ASSIGN: return "^=";
    case T_LSHIFT_ASSIGN: return "<<="; case T_RSHIFT_ASSIGN: return ">>=";
    default: return "?";
    }
}

static void emit_expr(FILE *out, Node *n) {
    if (!n) return;
    switch (n->type) {
    case N_INT_LIT:
        fprintf(out, "%d", n->ival);
        break;
    case N_CHAR_LIT:
        if (n->ival == 10) fprintf(out, "'\\n'");
        else if (n->ival == 9) fprintf(out, "'\\t'");
        else if (n->ival == 13) fprintf(out, "'\\r'");
        else if (n->ival == 0) fprintf(out, "'\\0'");
        else if (n->ival == 92) fprintf(out, "'\\\\'");
        else if (n->ival == 39) fprintf(out, "'\\''");
        else fprintf(out, "'%c'", n->ival);
        break;
    case N_IDENT:
        fprintf(out, "%s", n->name);
        break;
    case N_BINARY:
        fprintf(out, "(");
        emit_expr(out, n->left);
        fprintf(out, " %s ", op_c(n->op));
        emit_expr(out, n->right);
        fprintf(out, ")");
        break;
    case N_UNARY:
        if (n->op == T_INC || n->op == T_DEC) {
            fprintf(out, "%s", op_c(n->op));
            emit_expr(out, n->left);
        } else {
            fprintf(out, "%s", op_c(n->op));
            emit_expr(out, n->left);
        }
        break;
    case N_POSTFIX:
        emit_expr(out, n->left);
        fprintf(out, "%s", op_c(n->op));
        break;
    case N_ASSIGN:
        emit_expr(out, n->left);
        fprintf(out, " %s ", op_c(n->op));
        emit_expr(out, n->right);
        break;
    case N_TERNARY:
        emit_expr(out, n->cond);
        fprintf(out, " ? ");
        emit_expr(out, n->left);
        fprintf(out, " : ");
        emit_expr(out, n->right);
        break;
    case N_CALL:
        fprintf(out, "%s()", n->name);
        break;
    case N_CAST:
        fprintf(out, "(int)");
        emit_expr(out, n->left);
        break;
    case N_SIZEOF:
        fprintf(out, "sizeof(int)");
        break;
    default:
        fprintf(out, "%d", n->ival);
        break;
    }
}

void codegen_generate(FILE *out, Node *prog) {
    fprintf(out,
        "/* Generated by GCL */\n"
        "#include <stdio.h>\n"
        "#include <stdlib.h>\n\n"
        "int main(void) {\n");
    for (Node *n = prog; n; n = n->next) {
        if (n->type == N_VAR_DECL) {
            fprintf(out, "    int %s", n->name);
            if (n->left) {
                fprintf(out, " = ");
                emit_expr(out, n->left);
            }
            fprintf(out, ";\n");
        }
    }
    fprintf(out, "    printf(\"OK\\n\");\n    return 0;\n}\n");
}
