Section "Device"
    Identifier "AMD Radeon"
    Driver "radeon"
    Option "AccelMethod" "EXA"
    Option "DRI" "3"
    Option "TearFree" "true"
    Option "SWCursor" "true"
EndSection

Section "Screen"
    Identifier "Default Screen"
    Device "AMD Radeon"
    DefaultDepth 24
EndSection
