#!/usr/bin/env python3
"""gen_gui_consts.py — generates the raygui constant list header.

WHY a generator: gcl_raygui.c used to expose ZERO of the ~354 enum constants
declared in raygui.h (GuiControl, GuiControlProperty, GuiDefaultProperty,
GuiState, GuiResult, GuiTextAlignment*, GuiTextWrapMode and the 257 GuiIconName
icons). Every GuiSetStyle call therefore had to be written with magic numbers.
Hand-copying the list into the module guarantees it drifts from raygui.h, so it
is derived instead - the same "single source -> generated table" rule that
tools/gen_native_db.py already follows.

Output: language/_SRC/Modules/gcl_raygui_consts.h
    #define GCL_RAYGUI_CONST_LIST(X)  X(NAME) X(NAME) ...
The module expands that once into fn_* accessors and once into table entries.
The file is not rewritten when the content is unchanged (keeps the module from
being recompiled for nothing - same MK-3 rule as the font/icon embeds).

Run: python tools/gen_gui_consts.py
"""
from __future__ import annotations

import platform
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES = ROOT / "language" / "_SRC" / "Modules"
OUT = MODULES / "gcl_raygui_consts.h"


def os_name() -> str:
    name = platform.system().lower()
    return "gnuLinux" if name == "linux" else name


RAYGUI_HEADER = ROOT / "_temp" / os_name() / "Raygui" / "src" / "raygui.h"

# Declared by raylib.h, only *referenced* by raygui.h: they belong to the Raylib
# module, so exposing them through Raygui would just duplicate the table.
RAYLIB_OWNED = {
    "BLANK", "MOUSE_LEFT_BUTTON",
    "KEY_BACKSPACE", "KEY_DOWN", "KEY_ENTER", "KEY_LEFT", "KEY_RIGHT", "KEY_UP",
}


def _strip_comments(src: str) -> str:
    src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
    return re.sub(r"//[^\n]*", " ", src)


def collect_names() -> list:
    """Every enum constant declared in raygui.h, in declaration order."""
    if not RAYGUI_HEADER.exists():
        return []
    src = _strip_comments(RAYGUI_HEADER.read_text(encoding="utf-8", errors="replace"))
    names, seen = [], set()
    for m in re.finditer(r"\benum\b[^{;]*\{(.*?)\}", src, re.S):
        for nm in re.finditer(r"\b([A-Z][A-Z0-9_]+)\b", m.group(1)):
            n = nm.group(1)
            if n.startswith("RAYGUI_") or n in RAYLIB_OWNED or n in seen:
                continue
            seen.add(n)
            names.append(n)
    return names


def build_content(names: list) -> str:
    lines = [
        "/* gcl_raygui_consts.h - GENERATED by tools/gen_gui_consts.py.",
        " * DO NOT EDIT BY HAND: the list is derived from raygui.h.",
        " *",
        " * Every raygui.h enum constant (GuiControl, GuiControlProperty,",
        " * GuiDefaultProperty, GuiState, GuiResult, GuiTextAlignment*,",
        " * GuiTextWrapMode and GuiIconName) is listed here once. The module",
        " * expands GCL_RAYGUI_CONST_LIST() twice: once into fn_<NAME> accessors,",
        " * once into g_entries[] so `Raygui.<NAME>` resolves.",
        " */",
        "#ifndef GCL_RAYGUI_CONSTS_H",
        "#define GCL_RAYGUI_CONSTS_H",
        "",
        f"/* {len(names)} constants */",
        "#define GCL_RAYGUI_CONST_LIST(X) \\",
    ]
    for i, n in enumerate(names):
        tail = "" if i + 1 == len(names) else " \\"
        lines.append(f"    X({n}){tail}")
    lines += ["", "#endif /* GCL_RAYGUI_CONSTS_H */", ""]
    return "\n".join(lines)


def main() -> int:
    names = collect_names()
    if not names:
        print(f"[gen_gui_consts] note: header not found, skipped: {RAYGUI_HEADER}",
              flush=True)
        return 0
    content = build_content(names)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    old = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if old == content:
        print(f"[gen_gui_consts] up to date: {OUT}", flush=True)
        return 0
    OUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"[gen_gui_consts] written: {OUT} ({len(names)} constants)", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
